"""Mock Policy Chunk Repository.

Provides pre-seeded in-memory policy text chunks for demo/testing without
requiring PostgreSQL + pgvector. Works without embeddings — in mock mode the
query_embedding is [] (LLM disabled), so we match purely by policy_type and
candidate_policy_ids instead of vector similarity.

⚠️  THIS IS MOCK DATA — FOR DEVELOPMENT AND DEMO PURPOSES ONLY ⚠️
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import List


@dataclass
class MockPolicyChunk:
    """Lightweight in-memory substitute for the SQLAlchemy PolicyChunk model.

    Used only in mock/demo mode — avoids pgvector dependency.
    """
    id: int
    policy_type: str
    policy_id: str
    policy_version: int
    section: str | None
    chunk_text: str
    chunk_metadata: dict = field(default_factory=dict)


# ── Pre-seeded policy text chunks ─────────────────────────────────────────────
# Text is drawn from real CMS LCD/NCD indication language, condensed for demo.
# In production, these are generated by the ingestion pipeline from actual PDFs.

_CHUNKS: list[MockPolicyChunk] = [

    # ── LCD L39054 — Epidural Injections for Pain Management ─────────────────
    MockPolicyChunk(
        id=1,
        policy_type="LCD",
        policy_id="L39054",
        policy_version=1,
        section="Indications",
        chunk_text=(
            "Epidural steroid injections (ESIs) are covered when the patient has a "
            "diagnosis of radiculopathy (ICD-10: M54.16, M54.17) confirmed by clinical "
            "examination and supported by imaging (MRI or CT). The procedure must be an "
            "applicable HCPCS service (64483, 64484) listed in the associated Billing and "
            "Coding Article A12345. Conservative therapy of at least 6 weeks duration must "
            "have been tried and failed prior to injection."
        ),
    ),
    MockPolicyChunk(
        id=2,
        policy_type="LCD",
        policy_id="L39054",
        policy_version=1,
        section="Limitations",
        chunk_text=(
            "The following diagnoses are non-covered under this LCD: routine general "
            "examination (Z00.00), encounters without clinical indication of spinal "
            "pathology. Injections performed solely for general pain without a confirmed "
            "structural diagnosis are not covered. Maximum of 3 injections per 6-month "
            "period unless clinical documentation supports additional treatment."
        ),
    ),
    MockPolicyChunk(
        id=3,
        policy_type="LCD",
        policy_id="L39054",
        policy_version=1,
        section="Documentation Requirements",
        chunk_text=(
            "Documentation must support the reasonable and necessary nature of the "
            "epidural injection. Required elements: (1) radiculopathy symptoms confirmed "
            "on MRI or CT imaging, (2) failure of conservative therapy for >= 6 weeks, "
            "(3) functional impairment documented in clinical notes, (4) physician "
            "attestation that procedure is medically necessary."
        ),
    ),

    # ── NCD 110.23 — Stem Cell Transplantation ───────────────────────────────
    MockPolicyChunk(
        id=4,
        policy_type="NCD",
        policy_id="NCD-110.23",
        policy_version=1,
        section="Coverage Indications",
        chunk_text=(
            "Allogeneic hematopoietic stem cell transplantation (allo-HSCT) is covered "
            "for Medicare beneficiaries with the following conditions when reasonable and "
            "necessary: Leukemia, Aplastic Anemia, Severe Combined Immunodeficiency "
            "disease (SCID), and Wiskott-Aldrich Syndrome. HCPCS codes 38240, 38241, "
            "38242 are applicable services under this NCD."
        ),
    ),
    MockPolicyChunk(
        id=5,
        policy_type="NCD",
        policy_id="NCD-110.23",
        policy_version=1,
        section="Coverage with Evidence Development",
        # optional=True: this is an alternative OR-branch (CED trial path for conditions
        # NOT in the standard covered list). It must NOT block a standard-coverage request.
        chunk_metadata={"optional": True},
        chunk_text=(
            "Allo-HSCT is covered for Medicare beneficiaries with the following "
            "indications ONLY when participating in approved prospective clinical studies "
            "meeting CED criteria: Myelodysplastic Syndromes, Multiple myeloma (Durie-"
            "Salmon Stage II or III), Myelofibrosis with DIPSS-plus intermediate-2 or "
            "High risk, Sickle cell disease that is severe and symptomatic."
        ),
    ),
    MockPolicyChunk(
        id=6,
        policy_type="NCD",
        policy_id="NCD-110.23",
        policy_version=1,
        section="Documentation Requirements",
        chunk_text=(
            "Documentation to support the reasonable and necessary nature of allo-HSCTs "
            "must speak to the serious illness of the patient, reasons why the patient is "
            "considered to have relapsed or refractory disease, relevant clinical "
            "contextual information such as age, frailty, performance status, "
            "cardiopulmonary function, and psychosocial support structures."
        ),
    ),

    # ── NCD 190.25 — Alpha-fetoprotein ───────────────────────────────────────
    MockPolicyChunk(
        id=7,
        policy_type="NCD",
        policy_id="NCD-190.25",
        policy_version=1,
        section="Indications",
        chunk_text=(
            "AFP (Alpha-fetoprotein) testing (HCPCS 82105, 82106) is covered for the "
            "diagnosis of hepatocellular carcinoma in high-risk patients such as those "
            "with alcoholic cirrhosis, cirrhosis of viral etiology, hemochromatosis, and "
            "alpha 1-antitrypsin deficiency. Also covered as a non-specific tumor "
            "associated antigen for germ cell neoplasms of the testis, ovary, "
            "retroperitoneum, and mediastinum."
        ),
    ),

    # ── NCD N123 (160.7.1) — TENS for Acute & Chronic Pain ──────────────────
    MockPolicyChunk(
        id=8,
        policy_type="NCD",
        policy_id="N123",
        policy_version=1,
        section="Coverage Indications",
        chunk_text=(
            "Transcutaneous Electrical Nerve Stimulation (TENS) (HCPCS 64550) is covered "
            "for acute post-operative pain and chronic intractable pain when conservative "
            "therapy has been tried and failed. Documentation must support that the patient "
            "has a diagnosis of chronic pain requiring neurostimulation therapy and that "
            "conventional pharmacological treatment has been inadequate or contraindicated."
        ),
    ),
    MockPolicyChunk(
        id=9,
        policy_type="NCD",
        policy_id="N123",
        policy_version=1,
        section="Limitations",
        chunk_text=(
            "TENS is not covered as initial therapy for acute pain; conservative measures "
            "must be attempted first. TENS for chronic non-cancer pain requires documented "
            "failure of conventional pharmacological treatment. Not covered for patients "
            "with implanted cardiac pacemakers due to electromagnetic interference risk. "
            "Patient must have failed conservative therapy for >= 6 weeks."
        ),
    ),
]

# ── Index: (policy_type.upper(), policy_id.upper()) → list of chunk ids ───────
_INDEX: dict[tuple[str, str], list[int]] = {}
for _chunk in _CHUNKS:
    _key = (_chunk.policy_type.upper(), _chunk.policy_id.upper())
    _INDEX.setdefault(_key, []).append(_chunk.id - 1)  # 0-based index into _CHUNKS


class MockPolicyChunkRepository:
    """In-memory Policy Chunk repository for development and testing.

    Ignores query_embedding (works even when LLM is disabled and embedding=[]).
    Returns chunks matched purely by policy_type + candidate_policy_ids.
    """

    def search_similar(
        self,
        query_embedding: List[float],
        policy_type: str,
        candidate_policy_ids: List[str],
        top_k: int = 5,
        threshold: float = 0.5,
    ) -> List[tuple]:
        """Return matching policy chunks as (chunk, distance) tuples.

        In mock mode:
        - Ignores query_embedding and threshold (no vector DB available).
        - Matches by policy_type and candidate_policy_ids.
        - Returns each chunk paired with a synthetic similarity distance of 0.1
          (→ similarity score = 0.9) so the demo shows high-confidence RAG hits.
        """
        results = []
        ptype = policy_type.upper()

        for pid in candidate_policy_ids:
            key = (ptype, pid.upper())
            indices = _INDEX.get(key, [])
            for idx in indices:
                chunk = _CHUNKS[idx]
                # Synthetic distance: 0.1 → similarity = 1.0 - 0.1 = 0.90
                results.append((chunk, 0.10))
                if len(results) >= top_k:
                    return results

        return results
